### ISSUE TITLE
Apex Compile failure

### ISSUE THREAD

**Issue by vcmont34** [tegeling/ConsentTools#27]
Hello, 
When trying to install the package in a Developer Sandbox I have some compilation errors. I've tried to install for Admin only, All user, specific profiles, it's always the same errors as follow :

1.  Apex compile failure
Apex class GetBookingScheduleTest: line 4, column 10: Invalid type: GetBookingScheduleBatch

2.  Apex compile failure
Apex class GetBookingScheduleTest: line 6, column 17: Method does not exist or incorrect signature: void schedule(String, String, GetBookingScheduleBatch) from the type System

3.  Apex compile failure
Apex class testContactSchedule: line 5, column 9: Invalid type: Scheduler_class

4.  Apex compile failure
Apex class testContactSchedule: line 7, column 17: Method does not exist or incorrect signature: void schedule(String, String, Scheduler_class) from the type System

5.  Apex compile failure
Apex class testCorporateClientSchedule: line 7, column 9: Invalid type: Schedular_CorpClient

6.  Apex compile failure
Apex class testCorporateClientSchedule: line 9, column 16: Method does not exist or incorrect signature: void schedule(String, String, Schedular_CorpClient) from the type System

7.  Apex compile failure
Apex class testIndividualClientSchedule: line 5, column 9: Invalid type: Schedular_IndClient

8.  Apex compile failure
Apex class testIndividualClientSchedule: line 7, column 16: Method does not exist or incorrect signature: void schedule(String, String, Schedular_IndClient) from the type System

Any help would be very much appreciated

![Compilation_Error](https://github.com/tegeling/ConsentTools/assets/118986785/05b65e89-bc8b-4222-979f-3f8458a5d14f)

**Comment by tegeling** [comment]
Try to install the package with the Advanced Option **Compile only the Apex in the package**. This will allow installation without compilation of all other Apex classes that are already installed (and somehow in an invalid state). The reported Apex compile failures are from other classes not part of this package.

<img width="926" alt="Screenshot 2023-12-06 at 15 49 38" src="https://github.com/tegeling/ConsentTools/assets/8126079/54743ce5-8ee4-402a-b094-86f5fec4421f">

**Comment by vcmont34** [comment]
I've just found the option to pick-up the compile APEX in package only, I was about to post it here (and admit how dumb I was with my beginner's mistake..) when I realized that you had already posted the solution. Now that's fast ! Thanks a million ! :) 👍👏
link about this topic : https://unofficialsf.com/troubleshooting-installation-of-unofficialsf-packages/

**Comment by tegeling** [comment]
Thanks for the update and sharing the link. Good luck with your privacy setup!
